apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: dev
spec:
  secretName: ingress-certificate
  acme:
    config:
    - domains:
      - training-user-1.training.weave.works
      http01:
        ingress: ""
        ingressClass: traefik
  dnsNames:
  - training-user-1.training.weave.works
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
  secretName: ingress-certificate
