apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: mighty-fine
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: mighty-fine
          servicePort: 3000
        path: /mighty-fine
  host: training-user-58.training.weave.works
status:
  loadBalancer: {}
