apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  creationTimestamp: null
  name: podinfo
  namespace: dev
spec:
  rules:
  - host: training-user-2.training.weave.works
    http:
      paths:
      - backend:
          serviceName: podinfo
          servicePort: 9898
          port: http
        path: /podinfo
  tls:
  - hosts:
    - training-user-2.training.weave.works
    secretName: ingress-certificate
status:
  loadBalancer: {}
